version: "3.10"
services:
  db_postgres_test:
    image: postgres:16.4-alpine
    container_name: postgres_16.4-container_liib_super_mngmnt_test
    environment:
      POSTGRES_USER: user_test
      POSTGRES_PASSWORD: password
      POSTGRES_DB: liib_super_mngmnt_test
    ports:
      - "54326:5432"
    restart: on-failure
  app_test:
    container_name: liib_super_mngmnt_app_test
    build: .
    command: bash -c 'while !</dev/tcp/db_postgres/5432; do sleep 1; done; tail -f /dev/null'
    depends_on:
      - db_postgres_test
    volumes:
      - .:/app/.